import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ConfirmProvider } from "@/components/ConfirmModal";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster
          position="top-center"
          theme="dark"
          toastOptions={{
            style: {
              background: "var(--color-soft-bg)",
              backdropFilter: "blur(var(--blur-md))",
              WebkitBackdropFilter: "blur(var(--blur-md))",
              border: "none",
            },
            classNames: {
              success: "!bg-green-600 !text-white",
              error: "!bg-red-600 !text-white",
              warning: "!bg-yellow-500 !text-black",
              info: "!bg-[var(--bg-opacity-80)] !text-white",
            },
          }}
        />
        <ConfirmProvider />
      </body>
    </html>
  );
}
